name: Test secret

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pass_secret:
    environment: testing
    uses: ./.github/workflows/forward-secret.yaml
    secrets:
      my-secret: ${{ secrets.ENVIRONMENT_SECRET }}
