name: Use secret

on:
  workflow_call:
    secrets:
      my-secret:
        required: true

jobs:
  use-secret:
    runs-on: ubuntu-22.04
    name: Use secret
    outputs:
      result: ${{ steps.check_result.outputs.result }}
    env:
      SECRET: ${{ secrets.my-secret }}
    steps:
      - run: echo "Success"
